name: Deploy to AWS with Zappa

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8
        run: flake8 Parcial1Big/Zappacsv/function.py Parcial1Big/Zappacsv/test_project.py --max-line-length=120

  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pytest boto3 beautifulsoup4 pandas

      - name: Run tests
        run: pytest Parcial1Big/Zappacsv/test_project.py --maxfail=1 --disable-warnings

  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install zappa boto3 awscli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1


      - name: Verify AWS credentials
        run: |
          aws sts get-caller-identity
          aws s3 ls

      - name: Deploy with Zappa
        env:
          AWS_PROFILE: default  # Se fuerza el uso del perfil por defecto
          AWS_REGION: us-east-1 # Se asegura de que boto3 use la región correcta
        run: |
          source venv/bin/activate
          export AWS_DEFAULT_REGION=us-east-1
          export AWS_REGION=us-east-1
          zappa update devi -s Parcial1Big/Zappacsv/zappa_settings.json
          
