name: Deploy to AWS with Zappa

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install flake8

      - name: Ejecutar Flake8
        run: flake8 Parcial1Big/Zappacsv/function.py Parcial1Big/Zappacsv/test_project.py --max-line-length=120

  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pytest boto3 beautifulsoup4 pandas

      - name: Run tests
        run: pytest Parcial1Big/Zappacsv/test_project.py --maxfail=1 --disable-warnings

  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Zappa
        run: pip install zappa

      - name: Deploy with Zappa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          zappa update devi -s Parcial1Big/Zappacsv/zappa_settings.json

