name: Deploy to AWS with Zappa

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install flake8

      - name: Run Flake8
        run: flake8 Parcial1Big/Zappacsv/function.py Parcial1Big/Zappacsv/test_project.py --max-line-length=120

  test:
    name: Run pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pytest boto3 beautifulsoup4 pandas

      - name: Run tests
        run: pytest Parcial1Big/Zappacsv/test_project.py --maxfail=1 --disable-warnings

  deploy:
    name: Deploy to AWS Lambda
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Create virtual environment
        run: python -m venv venv

      - name: Activate virtual environment and install dependencies
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install zappa boto3 awscli

      - name: Set up AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source venv/bin/activate
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region us-east-1

      - name: Deploy with Zappa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source venv/bin/activate
          if zappa status devi 2>&1 | grep -q "Error"; then
            echo "Function not found. Running 'zappa deploy'..."
            zappa deploy devi -s Parcial1Big/Zappacsv/zappa_settings.json
          else
            echo "Function exists. Running 'zappa update'..."
            zappa update devi -s Parcial1Big/Zappacsv/zappa_settings.json
          fi

